### ISSUE TITLE
Files will not be re-generated if they already exist

### ISSUE THREAD

**Issue by cameron-brown-future** [rhys-vdw/ts-auto-guard#153]
Running the CLI command on a file (in this case `npx ts-auto-guard /project/src/module/index.types.ts`) more than once will cause this error:
```
(node:21607) UnhandledPromiseRejectionWarning: Error: Did you mean to provide the overwrite option? A source file already exists at the provided file path: /project/src/module/index.types.guard.ts
    at CompilerFactory.throwIfFileExists (/project/node_modules/ts-morph/dist/ts-morph.js:18329:15)
    at CompilerFactory.createSourceFileFromText (/project/node_modules/ts-morph/dist/ts-morph.js:18322:14)
    at CompilerFactory.createSourceFile (/project/node_modules/ts-morph/dist/ts-morph.js:18316:21)
    at Project.createSourceFile (/project/node_modules/ts-morph/dist/ts-morph.js:19303:46)
    at /project/node_modules/ts-auto-guard/lib/index.js:647:31
    at Array.forEach (<anonymous>)
    at processProject (/project/node_modules/ts-auto-guard/lib/index.js:611:24)
    at Object.<anonymous> (/project/node_modules/ts-auto-guard/lib/index.js:570:13)
    at step (/project/node_modules/ts-auto-guard/lib/index.js:34:23)
    at Object.next (/project/node_modules/ts-auto-guard/lib/index.js:15:53)
```

This is with `ts-morph@9.1.0`, unsure if this is new or expected behaviour.

The solution should either:

1. Provide the `{overwrite:true}` option to the call to `project.createSourceFile`
2. Carry an option from the CLI into this call, so it can be specified while calling the `ts-auto-guard` command

**Comment by rhys-vdw** [comment]
Duplicate of #150

**Comment by cameron-brown-future** [comment]
Ahh, I see in #150 the core problem is a bit more complex than I've made it out to be, I may dig into that later but this solution works for now

**Comment by rhys-vdw** [comment]
I think `overwrite: true` is the right solution.
